title: Maxwell B. Strome # your name (or website title) here
logo: "/images/work.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  410-371-6247    mbs2241@columbia.edu
  <br><br>
  Machine learning enthusiast. Can we make a conscious artifact? 
  <br><br>
  <a href="https://www.linkedin.com/in/maxwell-strome-778401150/">LinkedIn Profile</a> 
  <br><br>
  <a href="resume">Resume</a>
  <br><br>
  <a href="blog">Blog</a>
  <br><br>
  <a href="https://github.com/maxstrome">Github</a>
  <br><br>
  <a href=".">Home</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-186938234-1 # your Google Analytics tracking ID here
