title: Maxwell B. Strome # your name (or website title) here
logo: "/images/work.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  410-371-6247    mbs2241@columbia.edu
  <br><br>
  Pursuing a masters degree in computer science at Columbia. Machine learning enthusiast. Can we make a conscious artifact? 
  <br><br>
  <a href="https://www.linkedin.com/in/maxwell-strome-778401150/">LinkedIn Profile</a> 
  <br><br>
  <a href="resume">Resume</a>
  <br><br>
  <a href=".">Home</a>
  <script>!(function () {
  let e = document.createElement("script"),
    t = document.head || document.getElementsByTagName("head")[0];
  (e.src =
    "https://cdn.jsdelivr.net/npm/rasa-webchat@1.x.x/lib/index.js"),
    // Replace 1.x.x with the version that you want
    (e.async = !0),
    (e.onload = () => {
      window.WebChat.default(
        {
          customData: { language: "en" },
          socketUrl: "https://bf-botfront.development.agents.botfront.cloud",
          // add other props here
        },
        null
      );
    }),
    t.insertBefore(e, t.firstChild);
})();
</script>
  
theme: jekyll-theme-minimal
google_analytics: UA-186938234-1 # your Google Analytics tracking ID here
